plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.144'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    compileOnly files('../mods/[方块宝可梦] Cobblemon-neoforge-1.8.0+1.21.1.jar')
    compileOnly files('../mods/cobblemonintegrations-neoforge-1.21.1-1.1.6.jar')
    compileOnly files(zipTree('../mods/kotlinforforge-5.12.0-all.jar').matching {
        include 'META-INF/jarjar/kotlin-stdlib-2.4.0.jar'
    })
}

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def replaceProperties = [
            minecraft_version_range: minecraft_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version
    ]
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir(generateModMetadata)
neoForge.ideSyncTask(generateModMetadata)

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
